# Generated by Django 4.2.7 on 2023-11-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worker_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_for_worker', models.IntegerField()),
                ('price_for_customer', models.IntegerField()),
                ('work_scope', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worker_app.categorysub')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worker_app.object')),
                ('work_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worker_app.worktype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker_app.worker')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker_app.worktype'),
        ),
        migrations.AddField(
            model_name='object',
            name='workers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker'),
        ),
    ]
