# Generated by Django 4.2.7 on 2023-11-16 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0004_alter_worktype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='category',
            field=models.ForeignKey(limit_choices_to={'object__id': django.db.models.expressions.OuterRef('object__id')}, on_delete=django.db.models.deletion.CASCADE, to='worker_app.category'),
        ),
    ]
