# Generated by Django 4.2.7 on 2023-11-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0005_alter_worktype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.category'),
        ),
    ]
