# Generated by Django 4.2.7 on 2023-11-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0006_alter_worktype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='object',
        ),
    ]
