# Generated by Django 4.2.7 on 2023-11-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0008_remove_shift_object_alter_worker_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Ед.изм.', 'verbose_name_plural': 'Ед.изм.'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Результат за день', 'verbose_name_plural': 'Результаты за день'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Тип работ', 'verbose_name_plural': 'Типы работ'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='value',
            field=models.IntegerField(verbose_name='Выполненный объём'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worktype', verbose_name='Тип работ'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker', verbose_name='Рабочий'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.IntegerField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=10, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.measurement', verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='price_for_customer',
            field=models.IntegerField(verbose_name='Цена для заказчика'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='price_for_worker',
            field=models.IntegerField(verbose_name='Цена для рабочих'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='total_scope',
            field=models.IntegerField(verbose_name='Общий объём'),
        ),
        migrations.CreateModel(
            name='WorkersBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField(verbose_name='Выплаченная сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.object', verbose_name='Объект')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Выплата рабочему',
                'verbose_name_plural': 'Выплаты рабочим',
            },
        ),
    ]
