# Generated by Django 4.2.7 on 2023-11-25 06:38

from django.db import migrations, models
import django.db.models.deletion
import worker_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0009_alter_category_options_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_pay', models.IntegerField(verbose_name='Дней к оплате')),
                ('rate', models.IntegerField(default=700, verbose_name='Сумма в день')),
                ('date', models.DateField(verbose_name='Дата выплаты')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.object', verbose_name='Объект')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Командировочная выплата',
                'verbose_name_plural': 'Командировочные выплаты',
                'unique_together': {('worker', 'object', 'period')},
            },
        ),
    ]
