# Generated by Django 4.2.7 on 2023-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0010_travelbenefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbenefits',
            name='period',
            field=models.CharField(choices=[], default=2012, max_length=7, verbose_name='За период'),
            preserve_default=False,
        ),
    ]
