# Generated by Django 4.2.7 on 2023-11-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0011_alter_travelbenefits_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbenefits',
            name='period',
            field=models.CharField(max_length=7, verbose_name='За период'),
        ),
    ]
