# Generated by Django 4.2.7 on 2023-11-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0012_alter_travelbenefits_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=700, verbose_name='Сумма в день')),
                ('date_start', models.DateField(verbose_name='Начало командировки')),
                ('date_finish', models.DateField(verbose_name='Окончание командировки')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.object', verbose_name='Объект')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker', verbose_name='Рабочий')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='travelbenefits',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travelbenefits',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worker_app.travel', verbose_name='Командировка'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='travelbenefits',
            unique_together={('travel', 'period')},
        ),
        migrations.RemoveField(
            model_name='travelbenefits',
            name='object',
        ),
        migrations.RemoveField(
            model_name='travelbenefits',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='travelbenefits',
            name='worker',
        ),
    ]
