# Generated by Django 4.2.7 on 2023-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0014_alter_travel_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание командировки'),
        ),
    ]
