# Generated by Django 4.2.7 on 2023-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0015_alter_travel_date_finish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelbenefits',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travelbenefits',
            name='paid_for_travel',
            field=models.IntegerField(default=1, verbose_name='Выплаченно за командировку'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='travelbenefits',
            name='days_to_pay',
        ),
        migrations.RemoveField(
            model_name='travelbenefits',
            name='period',
        ),
    ]
