# Generated by Django 4.2.7 on 2023-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0016_alter_travelbenefits_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Командировка', 'verbose_name_plural': 'Командировки'},
        ),
        migrations.AddField(
            model_name='worker',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Аккаунт подтвеждён'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telegram_id',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Телеграм_id'),
        ),
    ]
