# Generated by Django 4.2.7 on 2023-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0017_alter_travel_options_worker_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм_id'),
        ),
    ]
