# Generated by Django 4.2.7 on 2023-12-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0018_alter_worker_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='confirmed',
        ),
    ]
