# Generated by Django 4.2.7 on 2023-12-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0020_remove_worker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм_id'),
        ),
    ]
