# Generated by Django 4.2.7 on 2023-12-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0022_worker_telephone_alter_worker_telegram_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('work_type', 'date', 'worker')},
        ),
    ]
