# Generated by Django 4.2.7 on 2024-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0024_alter_category_options_alter_object_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktype',
            old_name='measurement_type',
            new_name='measurement',
        ),
    ]
